language: java
jdk: openjdk8

notifications:
  email:
    recipients:
      - a.arshinkov97@gmail.com
    on_failure: always

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)